services:
 mariadb:
 container_name: web-mariadb-16
 hostname: mariadb
 image: mariadb:10.5
 restart: always
 environment:
 MARIADB_ROOT_PASSWORD: password
 MARIADB_DATABASE: 16_Calculatordb
 MARIADB_USER: root
 MARIADB_PASSWORD: password
 ports:
 - "0.0.0.0:5056:3306"
    
 web:
 container_name: 16_Calculatordb
 hostname: app
 build: .
 ports:
 - "0.0.0.0:5016:5016"
