version: "3.9"

services:
  web:
    build: .
    container_name: furnace_app
    ports:
      - "8000:8000"
    # Команда для запуска Django без миграций
    command: python manage.py runserver 0.0.0.0:8000